[package]
name = "tic-tac-tui"
version = "0.1.0"
description = "A simple tui tic tac toe game"
authors = ["John Schoeman <johnschoeman1617@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
